# Generated by Django 5.2.16 on 2026-07-25 06:02

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("appointments", "0002_alter_appointment_scheduled_end"),
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Bill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "bill_number",
                    models.CharField(
                        editable=False,
                        help_text="Auto-generated: INV-YYYY-NNNNN.",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("FINALIZED", "Finalized"),
                            ("PARTIAL", "Partially Paid"),
                            ("PAID", "Paid"),
                            ("CLOSED", "Closed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=15,
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Sum of item line totals.",
                        max_digits=10,
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Flat discount applied after subtotal.",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Percentage tax rate (e.g., 18.00 for 18% GST).",
                        max_digits=4,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Auto-computed from tax_rate.",
                        max_digits=10,
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Final amount due.",
                        max_digits=10,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("finalized_at", models.DateTimeField(blank=True, null=True)),
                (
                    "appointment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bill",
                        to="appointments.appointment",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_bills",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "finalized_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="finalized_bills",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        help_text="Denormalized from appointment.patient for query speed.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bills",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bill",
                "verbose_name_plural": "Bills",
                "db_table": "billing_bill",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ServiceCatalog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("CONSULTATION", "Consultation"),
                            ("LABORATORY", "Laboratory"),
                            ("IMAGING", "Imaging"),
                            ("PROCEDURE", "Procedure"),
                            ("ROOM", "Room / Ward"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=20,
                    ),
                ),
                (
                    "default_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                ("is_taxable", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Service (catalog)",
                "verbose_name_plural": "Services (catalog)",
                "db_table": "billing_service_catalog",
                "ordering": ["category", "code"],
                "indexes": [
                    models.Index(fields=["category"], name="billing_ser_categor_a8cdf8_idx"),
                    models.Index(fields=["name"], name="billing_ser_name_c018f6_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="BillItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Overrides service.name on this bill. Leave blank for default.",
                        max_length=200,
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Snapshot of price. Defaults to service.default_price.",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                (
                    "quantity",
                    models.PositiveSmallIntegerField(default=1, help_text="Number of units."),
                ),
                (
                    "line_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        editable=False,
                        help_text="Auto: unit_price × quantity.",
                        max_digits=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "bill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="billing.bill",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        limit_choices_to={"is_active": True},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bill_items",
                        to="billing.servicecatalog",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bill item",
                "verbose_name_plural": "Bill items",
                "db_table": "billing_bill_item",
                "ordering": ["id"],
            },
        ),
        migrations.AddIndex(
            model_name="bill",
            index=models.Index(fields=["status"], name="billing_bil_status_ddee07_idx"),
        ),
        migrations.AddIndex(
            model_name="bill",
            index=models.Index(fields=["patient"], name="billing_bil_patient_2ca142_idx"),
        ),
        migrations.AddIndex(
            model_name="bill",
            index=models.Index(fields=["-created_at"], name="billing_bil_created_0df0b9_idx"),
        ),
        migrations.AddIndex(
            model_name="billitem",
            index=models.Index(fields=["bill"], name="billing_bil_bill_id_896040_idx"),
        ),
        migrations.AddConstraint(
            model_name="billitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gte", 1)), name="bill_item_quantity_positive"
            ),
        ),
    ]
