# Generated by Django 5.2.16 on 2026-07-25 06:24

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0002_alter_bill_bill_number_alter_bill_discount_amount_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="received_at",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="payment",
            name="reference",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("COMPLETED", "Completed"),
                    ("FAILED", "Failed"),
                    ("REFUNDED", "Refunded"),
                ],
                default="COMPLETED",
                max_length=15,
            ),
        ),
        migrations.CreateModel(
            name="InsuranceClaim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        help_text="Insurance company name (e.g., 'Star Health').", max_length=100
                    ),
                ),
                (
                    "policy_number",
                    models.CharField(help_text="Patient's insurance policy number.", max_length=50),
                ),
                (
                    "claim_number",
                    models.CharField(
                        blank=True,
                        help_text="Insurer's tracking number (assigned after submission).",
                        max_length=50,
                    ),
                ),
                (
                    "amount_claimed",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                    ),
                ),
                (
                    "amount_approved",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUBMITTED", "Submitted"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("PAID", "Paid"),
                        ],
                        default="SUBMITTED",
                        max_length=15,
                    ),
                ),
                ("rejection_reason", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "bill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="insurance_claims",
                        to="billing.bill",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_insurance_claims",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "linked_payment",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="insurance_claim",
                        to="billing.payment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Insurance claim",
                "verbose_name_plural": "Insurance claims",
                "db_table": "billing_insurance_claim",
                "ordering": ["-submitted_at"],
                "indexes": [
                    models.Index(fields=["bill"], name="billing_ins_bill_id_459beb_idx"),
                    models.Index(fields=["status"], name="billing_ins_status_82a9f8_idx"),
                ],
            },
        ),
    ]
