# Generated by Django 5.2.16 on 2026-07-25 06:27

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0003_alter_payment_amount_alter_payment_received_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="insuranceclaim",
            name="claim_number",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="insuranceclaim",
            name="policy_number",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="insuranceclaim",
            name="provider",
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name="Refund",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Refund amount in INR.",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("CASH", "Cash"),
                            ("CARD", "Card reversal"),
                            ("UPI", "UPI"),
                            ("NETBANKING", "Net Banking"),
                            ("INSURANCE", "Insurance write-off"),
                        ],
                        default="CASH",
                        help_text="How the money was returned to the patient.",
                        max_length=15,
                    ),
                ),
                ("reason", models.TextField(help_text="Why this refund was issued.")),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        help_text="External reference (bank ref, cheque number).",
                        max_length=100,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("processed_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="refunds",
                        to="billing.payment",
                    ),
                ),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processed_refunds",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Refund",
                "verbose_name_plural": "Refunds",
                "db_table": "billing_refund",
                "ordering": ["-processed_at", "-created_at"],
                "indexes": [
                    models.Index(fields=["payment"], name="billing_ref_payment_86d195_idx"),
                    models.Index(fields=["-processed_at"], name="billing_ref_process_787c04_idx"),
                ],
            },
        ),
    ]
