# Generated by Django 5.2.16 on 2026-07-29 07:27

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0004_alter_insuranceclaim_claim_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="refund",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
        migrations.AlterField(
            model_name="refund",
            name="method",
            field=models.CharField(
                choices=[
                    ("CASH", "Cash"),
                    ("CARD", "Card reversal"),
                    ("UPI", "UPI"),
                    ("NETBANKING", "Net Banking"),
                    ("INSURANCE", "Insurance write-off"),
                ],
                default="CASH",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="refund",
            name="reference",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
