version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: Asia/Kolkata
    open-pull-requests-limit: 5
    reviewers:
      - swayam0406
    commit-message:
      prefix: "chore(deps)"
    labels:
      - dependencies

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: monthly
    commit-message:
      prefix: "chore(docker)"
    labels:
      - dependencies

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    commit-message:
      prefix: "chore(ci)"
    labels:
      - dependencies