# Generated by Django 5.2.16 on 2026-07-24 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ConditionCatalog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="ICD-10 code (e.g., J06.9).", max_length=10, unique=True
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable name (e.g., 'Acute upper respiratory infection').",
                        max_length=200,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("RESPIRATORY", "Respiratory"),
                            ("CARDIOVASCULAR", "Cardiovascular"),
                            ("DIGESTIVE", "Digestive"),
                            ("ENDOCRINE", "Endocrine"),
                            ("MUSCULOSKELETAL", "Musculoskeletal"),
                            ("INFECTIOUS", "Infectious"),
                            ("MENTAL", "Mental Health"),
                            ("NEUROLOGICAL", "Neurological"),
                            ("DERMATOLOGICAL", "Dermatological"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Condition (catalog)",
                "verbose_name_plural": "Conditions (catalog)",
                "db_table": "medical_records_condition_catalog",
                "ordering": ["code"],
                "indexes": [
                    models.Index(fields=["category"], name="medical_rec_categor_aa9b4e_idx"),
                    models.Index(fields=["name"], name="medical_rec_name_a79422_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="MedicationCatalog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Generic or brand name (e.g., 'Paracetamol').", max_length=100
                    ),
                ),
                (
                    "strength",
                    models.CharField(
                        help_text="Strength (e.g., '500mg', '5mg/5ml').", max_length=50
                    ),
                ),
                (
                    "form",
                    models.CharField(
                        choices=[
                            ("TABLET", "Tablet"),
                            ("CAPSULE", "Capsule"),
                            ("SYRUP", "Syrup"),
                            ("INJECTION", "Injection"),
                            ("OINTMENT", "Ointment"),
                            ("DROPS", "Drops"),
                            ("INHALER", "Inhaler"),
                            ("OTHER", "Other"),
                        ],
                        default="TABLET",
                        max_length=20,
                    ),
                ),
                ("manufacturer", models.CharField(blank=True, max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Medication (catalog)",
                "verbose_name_plural": "Medications (catalog)",
                "db_table": "medical_records_medication_catalog",
                "ordering": ["name", "strength"],
                "indexes": [models.Index(fields=["name"], name="medical_rec_name_3d745b_idx")],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("name", "strength", "form"),
                        name="unique_medication_name_strength_form",
                    )
                ],
            },
        ),
    ]
