# Generated by Django 5.2.16 on 2026-07-24 05:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0002_alter_appointment_scheduled_end"),
        ("medical_records", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="conditioncatalog",
            name="code",
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name="conditioncatalog",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="medicationcatalog",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="medicationcatalog",
            name="strength",
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name="MedicalRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "appointment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="medical_record",
                        to="appointments.appointment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Medical Record",
                "verbose_name_plural": "Medical Records",
                "db_table": "medical_records_medical_record",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Vitals",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("bp_systolic", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("bp_diastolic", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("pulse", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("respiratory_rate", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("spo2", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "temperature",
                    models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
                ),
                (
                    "weight_kg",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
                ),
                (
                    "height_cm",
                    models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
                ),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "medical_record",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vitals",
                        to="medical_records.medicalrecord",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recorded_vitals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Vitals",
                "verbose_name_plural": "Vitals",
                "db_table": "medical_records_vitals",
            },
        ),
    ]
