# Generated by Django 5.2.16 on 2026-07-24 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical_records", "0002_alter_conditioncatalog_code_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Diagnosis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Free-form clinical detail beyond the coded condition.",
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False, help_text="Marks this as the visit's primary diagnosis."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "condition",
                    models.ForeignKey(
                        limit_choices_to={"is_active": True},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="diagnoses",
                        to="medical_records.conditioncatalog",
                    ),
                ),
                (
                    "medical_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diagnoses",
                        to="medical_records.medicalrecord",
                    ),
                ),
            ],
            options={
                "verbose_name": "Diagnosis",
                "verbose_name_plural": "Diagnoses",
                "db_table": "medical_records_diagnosis",
                "ordering": ["-is_primary", "created_at"],
                "indexes": [
                    models.Index(fields=["medical_record"], name="medical_rec_medical_9dd4d7_idx"),
                    models.Index(fields=["condition"], name="medical_rec_conditi_e95b24_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("medical_record", "condition"), name="unique_diagnosis_per_record"
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("is_primary", True)),
                        fields=("medical_record",),
                        name="one_primary_diagnosis_per_record",
                    ),
                ],
            },
        ),
    ]
