# Generated by Django 5.2.16 on 2026-07-24 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical_records", "0003_diagnosis"),
    ]

    operations = [
        migrations.CreateModel(
            name="Prescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "valid_until",
                    models.DateField(
                        blank=True,
                        help_text="Date after which the prescription is no longer valid.",
                        null=True,
                    ),
                ),
                (
                    "general_instructions",
                    models.TextField(
                        blank=True,
                        help_text="Applies to the whole prescription (e.g., 'Take with food').",
                    ),
                ),
                (
                    "follow_up_after_days",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="Recommended follow-up window in days.", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "medical_record",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prescription",
                        to="medical_records.medicalrecord",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prescription",
                "verbose_name_plural": "Prescriptions",
                "db_table": "medical_records_prescription",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PrescriptionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "dose",
                    models.CharField(
                        help_text="e.g., '1 tablet', '10 ml', '2 puffs'.", max_length=50
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("OD", "Once daily"),
                            ("BID", "Twice daily"),
                            ("TID", "Three times daily"),
                            ("QID", "Four times daily"),
                            ("Q4H", "Every 4 hours"),
                            ("Q6H", "Every 6 hours"),
                            ("Q8H", "Every 8 hours"),
                            ("HS", "At bedtime"),
                            ("PRN", "As needed"),
                            ("STAT", "Immediately (single dose)"),
                        ],
                        default="BID",
                        max_length=10,
                    ),
                ),
                (
                    "duration_days",
                    models.PositiveSmallIntegerField(
                        default=5, help_text="Number of days to continue this medication."
                    ),
                ),
                (
                    "instructions",
                    models.CharField(
                        blank=True,
                        help_text="e.g., 'After meals', 'With warm water'.",
                        max_length=200,
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Display order on the prescription."
                    ),
                ),
                (
                    "medication",
                    models.ForeignKey(
                        limit_choices_to={"is_active": True},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="prescription_items",
                        to="medical_records.medicationcatalog",
                    ),
                ),
                (
                    "prescription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="medical_records.prescription",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prescription item",
                "verbose_name_plural": "Prescription items",
                "db_table": "medical_records_prescription_item",
                "ordering": ["order", "id"],
                "indexes": [
                    models.Index(fields=["prescription"], name="medical_rec_prescri_249d5c_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("prescription", "medication"),
                        name="unique_medication_per_prescription",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("duration_days__gte", 1)),
                        name="prescription_item_duration_positive",
                    ),
                ],
            },
        ),
    ]
