# Generated by Django 5.2.16 on 2026-07-24 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical_records", "0004_prescription_prescriptionitem"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="medicalrecord",
            name="chief_complaint",
            field=models.CharField(
                blank=True, help_text="One-line summary of why the patient came.", max_length=300
            ),
        ),
        migrations.AddField(
            model_name="medicalrecord",
            name="clinical_notes",
            field=models.TextField(
                blank=True, help_text="Additional clinical notes (visible to patient)."
            ),
        ),
        migrations.AddField(
            model_name="medicalrecord",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_medical_records",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="medicalrecord",
            name="examination_findings",
            field=models.TextField(blank=True, help_text="Clinical examination observations."),
        ),
        migrations.AddField(
            model_name="medicalrecord",
            name="follow_up_recommendation",
            field=models.TextField(
                blank=True, help_text="e.g., 'Return in 2 weeks if symptoms persist.'"
            ),
        ),
        migrations.AddField(
            model_name="medicalrecord",
            name="history_present_illness",
            field=models.TextField(
                blank=True,
                help_text="Narrative — onset, symptoms, progression, aggravating/relieving factors.",
            ),
        ),
        migrations.AddField(
            model_name="medicalrecord",
            name="is_locked",
            field=models.BooleanField(
                default=False,
                help_text="True once the appointment is completed. Prevents further edits via forms.",
            ),
        ),
        migrations.AddField(
            model_name="medicalrecord",
            name="locked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="medicalrecord",
            name="private_notes",
            field=models.TextField(
                blank=True, help_text="Doctor-only notes. NEVER shown to the patient."
            ),
        ),
    ]
