# Generated by Django 5.2.16 on 2026-07-29 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("billing", "0004_alter_insuranceclaim_claim_number_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LabTestProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "sample_type",
                    models.CharField(
                        choices=[
                            ("BLOOD", "Blood"),
                            ("URINE", "Urine"),
                            ("STOOL", "Stool"),
                            ("SWAB", "Swab"),
                            ("OTHER", "Other"),
                        ],
                        default="BLOOD",
                        max_length=10,
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True,
                        help_text="Measurement unit (e.g., 'mg/dL', 'mmol/L', 'g/dL').",
                        max_length=20,
                    ),
                ),
                (
                    "reference_range",
                    models.CharField(
                        blank=True,
                        help_text="Normal range (e.g., '70-100', '<200').",
                        max_length=100,
                    ),
                ),
                (
                    "turnaround_hours",
                    models.PositiveSmallIntegerField(
                        default=24,
                        help_text="Expected time from sample collection to result (hours).",
                    ),
                ),
                (
                    "preparation_notes",
                    models.TextField(
                        blank=True,
                        help_text="Patient preparation instructions (e.g., 'Fasting required 12 hours prior').",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "service",
                    models.OneToOneField(
                        help_text="Must be a ServiceCatalog entry with category=LABORATORY.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lab_profile",
                        to="billing.servicecatalog",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lab test profile",
                "verbose_name_plural": "Lab test profiles",
                "db_table": "laboratory_test_profile",
                "ordering": ["service__code"],
            },
        ),
    ]
