# Generated by Django 5.2.16 on 2026-07-29 07:27

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0005_alter_refund_amount_alter_refund_method_and_more"),
        ("laboratory", "0001_initial"),
        ("medical_records", "0005_medicalrecord_chief_complaint_and_more"),
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="labtestprofile",
            name="preparation_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="labtestprofile",
            name="reference_range",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="labtestprofile",
            name="service",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lab_profile",
                to="billing.servicecatalog",
            ),
        ),
        migrations.AlterField(
            model_name="labtestprofile",
            name="turnaround_hours",
            field=models.PositiveSmallIntegerField(default=24),
        ),
        migrations.AlterField(
            model_name="labtestprofile",
            name="unit",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name="LabOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "order_number",
                    models.CharField(
                        editable=False,
                        help_text="Auto-generated: LAB-YYYY-NNNNN.",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ORDERED", "Ordered"),
                            ("SAMPLE_COLLECTED", "Sample Collected"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="ORDERED",
                        max_length=20,
                    ),
                ),
                (
                    "clinical_notes",
                    models.TextField(
                        blank=True,
                        help_text="Doctor's notes for the lab (e.g., 'Rule out dengue').",
                    ),
                ),
                ("sample_collected_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "medical_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lab_orders",
                        to="medical_records.medicalrecord",
                    ),
                ),
                (
                    "ordered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ordered_lab_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        help_text="Denormalized from medical_record.appointment.patient.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lab_orders",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lab order",
                "verbose_name_plural": "Lab orders",
                "db_table": "laboratory_lab_order",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LabOrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Snapshot of price at order time.",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                (
                    "result_value",
                    models.CharField(
                        blank=True,
                        help_text="Measured value (e.g., '5.4', 'Negative').",
                        max_length=100,
                    ),
                ),
                (
                    "result_unit",
                    models.CharField(
                        blank=True, help_text="Unit (auto-copied from lab profile).", max_length=20
                    ),
                ),
                (
                    "reference_range",
                    models.CharField(
                        blank=True,
                        help_text="Normal range (auto-copied from lab profile).",
                        max_length=100,
                    ),
                ),
                ("is_abnormal", models.BooleanField(default=False)),
                ("result_notes", models.TextField(blank=True)),
                ("resulted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "is_billed",
                    models.BooleanField(
                        default=False,
                        help_text="True once this item has been appended to the visit's bill.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="laboratory.laborder",
                    ),
                ),
                (
                    "resulted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resulted_lab_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        limit_choices_to={"category": "LABORATORY", "is_active": True},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lab_order_items",
                        to="billing.servicecatalog",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lab order item",
                "verbose_name_plural": "Lab order items",
                "db_table": "laboratory_lab_order_item",
                "ordering": ["id"],
            },
        ),
        migrations.AddIndex(
            model_name="laborder",
            index=models.Index(fields=["status"], name="laboratory__status_1361da_idx"),
        ),
        migrations.AddIndex(
            model_name="laborder",
            index=models.Index(fields=["patient"], name="laboratory__patient_00c38d_idx"),
        ),
        migrations.AddIndex(
            model_name="laborder",
            index=models.Index(fields=["-created_at"], name="laboratory__created_96857f_idx"),
        ),
        migrations.AddIndex(
            model_name="laborderitem",
            index=models.Index(fields=["order"], name="laboratory__order_i_2f4b05_idx"),
        ),
        migrations.AddIndex(
            model_name="laborderitem",
            index=models.Index(fields=["is_billed"], name="laboratory__is_bill_00658b_idx"),
        ),
    ]
