# Generated by Django 5.2.16 on 2026-07-29 17:14

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("medical_records", "0005_medicalrecord_chief_complaint_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "quantity_on_hand",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Current stock (in dispensing units: tablets, vials, etc.).",
                    ),
                ),
                (
                    "reorder_threshold",
                    models.PositiveIntegerField(
                        default=10,
                        help_text="Trigger a low-stock alert when quantity_on_hand ≤ this.",
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Purchase cost per unit.",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                (
                    "unit_sale_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Sale price billed to the patient per unit.",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                ("last_restocked_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "medication",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory",
                        to="medical_records.medicationcatalog",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inventory item",
                "verbose_name_plural": "Inventory items",
                "db_table": "pharmacy_inventory_item",
                "ordering": ["medication__name"],
            },
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("RECEIVE", "Received (purchase)"),
                            ("DISPENSE", "Dispensed"),
                            ("ADJUST", "Adjustment"),
                            ("EXPIRE", "Expired / Damaged"),
                            ("TRANSFER", "Transferred"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        help_text="Signed: positive = added to stock, negative = removed."
                    ),
                ),
                (
                    "balance_after",
                    models.PositiveIntegerField(
                        help_text="Stock level after this movement (denormalized for audit)."
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                ("reference", models.CharField(blank=True, max_length=100)),
                ("performed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "inventory_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movements",
                        to="pharmacy.inventoryitem",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_movements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Stock movement",
                "verbose_name_plural": "Stock movements",
                "db_table": "pharmacy_stock_movement",
                "ordering": ["-performed_at"],
            },
        ),
        migrations.AddIndex(
            model_name="inventoryitem",
            index=models.Index(fields=["quantity_on_hand"], name="pharmacy_in_quantit_647371_idx"),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(fields=["inventory_item"], name="pharmacy_st_invento_049e18_idx"),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(fields=["-performed_at"], name="pharmacy_st_perform_ea96d5_idx"),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(fields=["movement_type"], name="pharmacy_st_movemen_b24e46_idx"),
        ),
        migrations.AddConstraint(
            model_name="stockmovement",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity", 0), _negated=True),
                name="stock_movement_quantity_nonzero",
            ),
        ),
    ]
