# Generated by Django 5.2.16 on 2026-07-31 13:30

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical_records", "0005_medicalrecord_chief_complaint_and_more"),
        ("patients", "0001_initial"),
        ("pharmacy", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockmovement",
            name="balance_after",
            field=models.PositiveIntegerField(),
        ),
        migrations.CreateModel(
            name="Dispense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "dispense_number",
                    models.CharField(
                        editable=False,
                        help_text="Auto-generated: DSP-YYYY-NNNNN.",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("DISPENSED", "Dispensed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=15,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("dispensed_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dispensed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dispensed_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        help_text="Denormalized from prescription.medical_record.appointment.patient.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dispenses",
                        to="patients.patient",
                    ),
                ),
                (
                    "prescription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dispenses",
                        to="medical_records.prescription",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dispense",
                "verbose_name_plural": "Dispenses",
                "db_table": "pharmacy_dispense",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DispenseItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "quantity_dispensed",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Snapshot of unit_sale_price at dispense time.",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                (
                    "line_total",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), editable=False, max_digits=10
                    ),
                ),
                (
                    "is_billed",
                    models.BooleanField(
                        default=False,
                        help_text="True once this item has been appended to the visit's bill.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dispense",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="pharmacy.dispense",
                    ),
                ),
                (
                    "inventory_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dispense_items",
                        to="pharmacy.inventoryitem",
                    ),
                ),
                (
                    "prescription_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dispense_items",
                        to="medical_records.prescriptionitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dispense item",
                "verbose_name_plural": "Dispense items",
                "db_table": "pharmacy_dispense_item",
                "ordering": ["id"],
            },
        ),
        migrations.AddIndex(
            model_name="dispense",
            index=models.Index(fields=["status"], name="pharmacy_di_status_a213e3_idx"),
        ),
        migrations.AddIndex(
            model_name="dispense",
            index=models.Index(fields=["patient"], name="pharmacy_di_patient_fe856c_idx"),
        ),
        migrations.AddIndex(
            model_name="dispense",
            index=models.Index(fields=["-created_at"], name="pharmacy_di_created_9ba873_idx"),
        ),
        migrations.AddIndex(
            model_name="dispenseitem",
            index=models.Index(fields=["dispense"], name="pharmacy_di_dispens_c3de1b_idx"),
        ),
        migrations.AddIndex(
            model_name="dispenseitem",
            index=models.Index(fields=["is_billed"], name="pharmacy_di_is_bill_1c5387_idx"),
        ),
    ]
