# Generated by Django 5.2.16 on 2026-07-29 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Admin"),
                    ("DOCTOR", "Doctor"),
                    ("NURSE", "Nurse"),
                    ("RECEPTIONIST", "Receptionist"),
                    ("PATIENT", "Patient"),
                    ("LAB_TECH", "Lab Technician"),
                ],
                default="PATIENT",
                help_text="Determines the user's access level within the HMS.",
                max_length=20,
            ),
        ),
    ]
