# Generated by Django 5.2.16 on 2026-07-23 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("doctors", "0002_alter_department_code_alter_department_description_and_more"),
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "scheduled_start",
                    models.DateTimeField(help_text="When the appointment is scheduled to begin."),
                ),
                (
                    "scheduled_end",
                    models.DateTimeField(help_text="Auto-computed from doctor's slot duration."),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Scheduled"),
                            ("CONFIRMED", "Confirmed"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                            ("NO_SHOW", "No-show"),
                        ],
                        default="SCHEDULED",
                        max_length=15,
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        help_text="Chief complaint or reason for visit.", max_length=200
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Free-form notes updated during and after the visit."
                    ),
                ),
                (
                    "cancelled_reason",
                    models.CharField(
                        blank=True,
                        help_text="Reason if the appointment was cancelled.",
                        max_length=200,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "booked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="booked_appointments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="appointments",
                        to="doctors.doctor",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="appointments",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Appointment",
                "verbose_name_plural": "Appointments",
                "db_table": "appointments_appointment",
                "ordering": ["-scheduled_start"],
                "indexes": [
                    models.Index(fields=["scheduled_start"], name="appointment_schedul_d6575a_idx"),
                    models.Index(
                        fields=["doctor", "scheduled_start"], name="appointment_doctor__88edfd_idx"
                    ),
                    models.Index(
                        fields=["patient", "scheduled_start"], name="appointment_patient_396ea6_idx"
                    ),
                    models.Index(fields=["status"], name="appointment_status_8fe9d7_idx"),
                ],
            },
        ),
    ]
