# Generated by Django 5.2.16 on 2026-07-23 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="scheduled_end",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                help_text="Auto-computed from doctor's slot duration on save.",
                null=True,
            ),
        ),
    ]
