# Generated by Django 5.2.16 on 2026-07-23 08:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(editable=False, help_text='Auto-generated hospital ID (e.g. MC-2026-00001).', max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('UNK', 'Unknown')], default='UNK', max_length=3)),
                ('marital_status', models.CharField(blank=True, choices=[('SINGLE', 'Single'), ('MARRIED', 'Married'), ('DIVORCED', 'Divorced'), ('WIDOWED', 'Widowed'), ('OTHER', 'Other')], max_length=20)),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 to 15 digits, optionally starting with +.', regex='^\\+?\\d{10,15}$')])),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address_line', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('pincode', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Enter a valid 6-digit Indian PIN code.', regex='^\\d{6}$')])),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 to 15 digits, optionally starting with +.', regex='^\\+?\\d{10,15}$')])),
                ('emergency_contact_relation', models.CharField(blank=True, max_length=30)),
                ('allergies', models.TextField(blank=True, help_text='Comma-separated list of known allergies.')),
                ('chronic_conditions', models.TextField(blank=True, help_text='e.g. diabetes, hypertension.')),
                ('current_medications', models.TextField(blank=True, help_text='Currently prescribed medications.')),
                ('is_active', models.BooleanField(default=True, help_text='Soft-delete flag. Deactivated patients are hidden from staff views.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_patients', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(blank=True, help_text='Optional link to a User account for portal access.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'db_table': 'patients_patient',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['patient_id'], name='patients_pa_patient_927c52_idx'), models.Index(fields=['phone'], name='patients_pa_phone_fc49bb_idx'), models.Index(fields=['last_name', 'first_name'], name='patients_pa_last_na_1b32a7_idx')],
            },
        ),
    ]
