# Generated by Django 5.2.16 on 2026-07-23 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Department name (e.g., Cardiology).", max_length=100, unique=True
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Short code used in reports and IDs (e.g., CARD).",
                        max_length=10,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Brief description of the department's services."
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Deactivate to hide from booking without deletion."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Department",
                "verbose_name_plural": "Departments",
                "db_table": "doctors_department",
                "ordering": ["name"],
            },
        ),
    ]
