# Generated by Django 5.2.16 on 2026-07-23 17:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="code",
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name="department",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="department",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="department",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("license_number", models.CharField(max_length=50, unique=True)),
                (
                    "specialty",
                    models.CharField(
                        help_text="Sub-specialty within the department (e.g., 'Interventional Cardiology').",
                        max_length=100,
                    ),
                ),
                (
                    "qualifications",
                    models.CharField(
                        help_text="Degrees, e.g., 'MBBS, MD (Cardiology)'.", max_length=200
                    ),
                ),
                ("years_of_experience", models.PositiveIntegerField(default=0)),
                (
                    "consultation_fee",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Fee per consultation in ₹.",
                        max_digits=8,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "consultation_duration_minutes",
                    models.PositiveSmallIntegerField(
                        default=15,
                        help_text="Length of one appointment slot, in minutes.",
                        validators=[django.core.validators.MinValueValidator(5)],
                    ),
                ),
                ("bio", models.TextField(blank=True)),
                (
                    "is_available_for_booking",
                    models.BooleanField(
                        default=True, help_text="Uncheck to temporarily stop new appointments."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="doctors",
                        to="doctors.department",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        limit_choices_to={"role": "DOCTOR"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctor_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Doctor",
                "verbose_name_plural": "Doctors",
                "db_table": "doctors_doctor",
                "ordering": ["user__first_name", "user__last_name"],
            },
        ),
        migrations.CreateModel(
            name="DoctorAvailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "weekday",
                    models.IntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ]
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availabilities",
                        to="doctors.doctor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Availability slot",
                "verbose_name_plural": "Availability slots",
                "db_table": "doctors_availability",
                "ordering": ["doctor", "weekday", "start_time"],
            },
        ),
        migrations.AddIndex(
            model_name="doctor",
            index=models.Index(fields=["department"], name="doctors_doc_departm_6f8e45_idx"),
        ),
        migrations.AddIndex(
            model_name="doctor",
            index=models.Index(
                fields=["is_available_for_booking"], name="doctors_doc_is_avai_c9856d_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="doctoravailability",
            constraint=models.UniqueConstraint(
                fields=("doctor", "weekday", "start_time"), name="unique_doctor_weekday_start"
            ),
        ),
        migrations.AddConstraint(
            model_name="doctoravailability",
            constraint=models.CheckConstraint(
                condition=models.Q(("start_time__lt", models.F("end_time"))),
                name="availability_start_before_end",
            ),
        ),
    ]
